# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 463d8315406bf309e40ddc560a2da7e4a4f97a4fa3ac36d4bd39e1e7fed99ee253056a51999a1d86fa8d56697479c1b9385eec6d8daa2d0d8d6b988629c6396d

test:
  secret_key_base: 35a7d54b961e26a1cb226cb63c818bef23d28ce023c3dcb06e1c0cd4ba1af54dee486220552710f855119055617a7ba73c75ffa9235f16aeb097efc3f884b4f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
